### ISSUE TITLE
Create JSON Schema for information storage

### ISSUE THREAD

**Issue by zacKolton** [zacKolton/COMP4560-deferred-exam-project#7]
Use pandas library 

```json
{
 courses: [
     {
       Math1240 : [COMP 1020, COMP 2010]
     }
   ]
}
```

**Comment by zacKolton** [comment]
![Screenshot 2024-02-17 at 2 27 33 PM](https://github.com/zacKolton/COMP4560-deferred-exam-project/assets/43692415/7c0dc98f-15b1-4007-84ff-c0bb69644ba8)

**Comment by bochacho** [comment]
Added Function that automatically creates JSON data as long as the input is valid

**Comment by zacKolton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Algorithm development](https://trello.com/c/u77lm8NL/31-algorithm-development)
